export const SONG_LIST_REQUESTED = 'SONG_LIST_REQUESTED';
export const SONG_LIST_RETRIEVED = 'SONG_LIST_RETRIEVED';
export const SONG_LIST_ITEM_CLICKED = 'SONG_LIST_ITEM_CLICKED';
export const SONG_LIST_SORTED = 'SONG_LIST_SORTED';

export const FILTER_LIST_LOADED = 'FILTER_LIST_LOADED';
export const FILTER_ITEM_CLICKED = 'FILTER_ITEM_CLICKED';

export const AUDIO_SOURCE_UPDATED = 'AUDIO_SOURCE_UPDATED';
export const AUDIO_FILE_LOADED = 'AUDIO_FILE_LOADED';
export const AUDIO_DURATION_SET = 'AUDIO_DURATION_SET';

export const AUDIO_ANALYSER_UPDATED = 'AUDIO_ANALYSER_UPDATED';
export const AUDIO_TIME_UPDATED = 'AUDIO_TIME_UPDATED';
export const AUDIO_BUFFERED = 'AUDIO_BUFFERED';
export const AUDIO_ENDED = 'AUDIO_ENDED';

export const AUDIO_PLAY_PAUSED = 'AUDIO_PLAY_PAUSED';
export const AUDIO_TRACK_CHANGED = 'AUDIO_TRACK_CHANGED';

export const AUDIO_SEEKED = 'AUDIO_SEEKED';

export const ARTWORK_LOADED = 'ARTWORK_LOADED';

