export const SONG_LIST_REQUESTED = 'SONG_LIST_REQUESTED';
export const SONG_LIST_RETRIEVED = 'SONG_LIST_RETRIEVED';
export const SONG_LIST_ITEM_CLICKED = 'SONG_LIST_ITEM_CLICKED';
export const SONG_LIST_SORTED = 'SONG_LIST_SORTED';

export const AUDIO_NODE_UPDATED = 'AUDIO_NODE_UPDATED';
export const AUDIO_FILE_LOADED = 'AUDIO_FILE_LOADED';
export const AUDIO_DURATION_SET = 'AUDIO_DURATION_SET';
export const AUDIO_ENDED = 'AUDIO_ENDED';
export const AUDIO_PLAY_PAUSED = 'AUDIO_PLAY_PAUSED';
export const AUDIO_SEEKED = 'AUDIO_SEEKED';
export const AUDIO_TIME_UPDATED = 'AUDIO_TIME_UPDATED';

