export const UI_RESET = 'UI_RESET';

export const SONG_LIST_REQUESTED = 'SONG_LIST_REQUESTED';
export const SONG_LIST_RETRIEVED = 'SONG_LIST_RETRIEVED';
export const SONG_LIST_ITEM_CLICKED = 'SONG_LIST_ITEM_CLICKED';
export const SONG_LIST_SORTED = 'SONG_LIST_SORTED';
export const SONG_LIST_QUEUE_ADDED = 'SONG_LIST_QUEUE_ADDED';
export const SONG_LIST_MENU_OPENED = 'SONG_LIST_MENU_OPENED';

export const FILTER_LIST_REQUESTED = 'FILTER_LIST_REQUESTED';
export const FILTER_LIST_RECEIVED = 'FILTER_LIST_RECEIVED';
export const FILTER_ITEM_CLICKED = 'FILTER_ITEM_CLICKED';

export const AUDIO_SOURCE_UPDATED = 'AUDIO_SOURCE_UPDATED';
export const AUDIO_FILE_LOADED = 'AUDIO_FILE_LOADED';
export const AUDIO_DURATION_SET = 'AUDIO_DURATION_SET';

export const AUDIO_ANALYSER_UPDATED = 'AUDIO_ANALYSER_UPDATED';
export const AUDIO_TIME_UPDATED = 'AUDIO_TIME_UPDATED';
export const AUDIO_BUFFERED = 'AUDIO_BUFFERED';
export const AUDIO_ENDED = 'AUDIO_ENDED';

export const AUDIO_PLAY_PAUSED = 'AUDIO_PLAY_PAUSED';
export const AUDIO_TRACK_CHANGED = 'AUDIO_TRACK_CHANGED';

export const AUDIO_SEEKED = 'AUDIO_SEEKED';

export const SEARCH_NAVIGATED = 'SEARCH_NAVIGATED';
export const SEARCH_SELECTED = 'SEARCH_SELECTED';
export const SEARCH_CHANGED = 'SEARCH_CHANGED';
export const SEARCH_RESULTS_RECEIVED = 'SEARCH_RESULTS_RECEIVED';
export const SEARCH_FOCUS_SET = 'SEARCH_FOCUS_SET';

