export const REQUEST_SONG_LIST = 'REQUEST_SONG_LIST';

export const REQUEST_FILTER_LIST = 'REQUEST_FILTER_LIST';

export const REQUEST_SEARCH_RESULTS = 'REQUEST_SEARCH_RESULTS';

export const REQUEST_SEARCHED_SONG_LIST = 'REQUEST_SEARCHED_SONG_LIST';

